{"name": "test_api2[item1]", "status": "failed", "statusDetails": {"message": "AssertionError: '操作成功' not found in '{\"returnCode\":\"1111\",\"returnMessage\":\"地址描述已存在，请修改！\"}'", "trace": "self = <TestCase.Test_Case2.Test_case1 object at 0x0000011BB4DDE310>\nitem = {'assertion': '操作成功', 'case_id': 2, 'data': 'town=110101&street=&subdistrict=&codeDesc=${product_name1}&pinyinCode=&addrCodeLng=&addrCodeLat=&SelectType=1&remark=&codeLevel=4&parentCodeId=110101', 'header': 'form', ...}\n\n    @pytest.mark.parametrize('item', Case().get_case(test_path, el[2]))\n    def test_api2(self, item):\n>       Common_Testcase().Testcase(sheet_name=el[2], url=item[\"url\"], data=item[\"data\"],\n                                   assertion=item[\"assertion\"],\n                                   regular=item[\"regular\"], sql=item[\"sql\"], sql_assertion=item[\"sql_assertion\"],\n                                   case_id=item[\"case_id\"], header=item[\"header\"], method=item[\"method\"], case_list=[])\n\nTestCase\\Test_Case2.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nCommon\\Common_testcase.py:21: in Testcase\n    Response_Assertion().assertion(response_data=response_data, case_id=case_id, case_list=case_list,\nCommon\\Response_assertion.py:19: in assertion\n    raise e\nCommon\\Response_assertion.py:13: in assertion\n    unittest.TestCase().assertIn(str(assertion), response_data)\nc:\\python\\python38\\lib\\unittest\\case.py:1179: in assertIn\n    self.fail(self._formatMessage(msg, standardMsg))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <unittest.case.TestCase testMethod=runTest>\nmsg = '\\'操作成功\\' not found in \\'{\"returnCode\":\"1111\",\"returnMessage\":\"地址描述已存在，请修改！\"}\\''\n\n    def fail(self, msg=None):\n        \"\"\"Fail immediately, with the given message.\"\"\"\n>       raise self.failureException(msg)\nE       AssertionError: '操作成功' not found in '{\"returnCode\":\"1111\",\"returnMessage\":\"地址描述已存在，请修改！\"}'\n\nc:\\python\\python38\\lib\\unittest\\case.py:753: AssertionError"}, "attachments": [{"name": "log", "source": "2ca6e28e-9fd5-424a-b9bb-23371facb7ab-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "item", "value": "{'case_id': 2, 'title': '地址增加', 'url': 'http://gxcr.etbc-enesys.eslink.net.cn/enesys-web/addrCode/insertAddrCode', 'method': 'post', 'header': 'form', 'data': 'town=110101&street=&subdistrict=&codeDesc=${product_name1}&pinyinCode=&addrCodeLng=&addrCodeLat=&SelectType=1&remark=&codeLevel=4&parentCodeId=110101', 'assertion': '操作成功', 'response': '{\"returnCode\":\"0000\",\"returnMessage\":\"操作成功！\"}', 'result': 'pass', 'regular': None, 'sql': '[\"SELECT * FROM address_code where addr_code_des =\\'${product_name1}\\'\"]', 'sql_assertion': '[\"${product_name1}\"]', 'sql_response': '{\\'1\\': \"{\\'addr_code_id\\': \\'110101014\\', \\'addr_code_level\\': \\'4\\', \\'addr_code_des\\': \\'888888\\', \\'node_name\\': None, \\'pinyin_code\\': None, \\'addr_code_lng\\': None, \\'addr_code_lat\\': None, \\'tenant_id\\': \\'ITQ8m46H1FpoaC2brNC52vLr06lv24LA\\', \\'code_id\\': \\'110101\\', \\'org_id\\': \\'075703\\', \\'open_cust_fee_price\\': None, \\'remark\\': \\'\\', \\'telphone\\': None, \\'old_data_flag\\': None}\"}', 'sql_result': 'pass'}"}], "start": 1600499844218, "stop": 1600499844808, "uuid": "6f785fa6-282f-4bd4-9f55-d2e8df40ac56", "historyId": "6d4c5b1814c60af5a38195217859ff6e", "testCaseId": "93d6628e45128ee878434a4d9a651018", "fullName": "TestCase.Test_Case2.Test_case1#test_api2", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "Test_Case2"}, {"name": "subSuite", "value": "Test_case1"}, {"name": "host", "value": "ylylt0161-2007"}, {"name": "thread", "value": "3812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.Test_Case2"}]}